### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Volont84** [sergiotocalini/jenkix#1]
Hi!
Can you please write a manual about using and testing this template? It would be grate for all new users.
As for me I get error "Unsupported item key" in Zabbix and "0" when manual running the script.
So maybe manual will help me to find my mistake.

**Comment by sergiotocalini** [comment]
Hi @Volont84 
I've just added the basic documentation to make it work. Let me know if you still have problems.

**Comment by AparnaNemani** [comment]
Hi,
I cannot find the documentation. Could you please share it again, since i am facing the same issue.

**Comment by sergiotocalini** [comment]
Hi,
You can find all the necessary steps on the README.md.
I am not sure what is your issue and if you did some change on your configurations but it should be covered by the documentation.
Best,
Sergio

**Comment by AparnaNemani** [comment]
Hi @sergiotocalini 

I followed all the steps from README.md , still i am getting Unsupported item key in zabbix

**Comment by sergiotocalini** [comment]
Hi @AparnaNemani ,
Did you restart the zabbix-agent service? you can check with zabbix_agentd -p
Also verify your installation include dir, the script is installing on /etc/zabbix/zabbix_agent.d. If your installation is different you will need to change this, take a look on deploy_zabbix.sh script where you can find all the command to setup your agent.
Regards,
Sergio

**Comment by itkroplis** [comment]
What is you zabbix version? Need 3.4 or younger!

**Comment by sergiotocalini** [comment]
I've been using with version 3.4 but the script should work for all you may need to adapt the template for different versions ;).

**Comment by AparnaNemani** [comment]
Hi Sergio,

Yes, i am restarting the zabbix agent and i have installed the script in the path /etc/zabbix/zabbix_agent.d. I did everything as per README.md. But i am getting output as 0(zero) for all items in zabbix.
Even on executing the jenkins.sh file individually i am getting the same output as 0. Kindly let me know the mistake. Please also let me know if jenkins.sh file needs to execute with any arguments.

Thanks.

**Comment by itkroplis** [comment]
username and password  its correctly entered?

**Comment by AparnaNemani** [comment]
yes @itkroplis
