### ISSUE TITLE
Received value […/jenkix.sh: line 201:   / 1000 : arithmetic syntax error

### ISSUE THREAD

**Issue by Tozapid** [sergiotocalini/jenkix#11]
Hello!
Sometimes I get an error from the Status item- `jenkix[job, active, some-job-in-jenkins, 30]`

```
#1215:20200401:044711.639 item "jenkins-server:jenkix[job, active, some-job-in-jenkins, 30]" became not supported: Received value [/etc/zabbix/scripts/jenkix.sh: line 201:   / 1000 : arithmetic syntax error/etc/zabbix/scripts/jenkix.sh: line 202:  (1585716431-)/86400 : arithmetic syntax error] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
```

I don’t quite understand where it comes from, I don’t see any errors in the terminal

```
/etc/zabbix/scripts/jenkix.sh -s "job" -a p="active" -a p="some-job-in-jenkins" -a p="30" -a p=""
1
```

**Comment by sergiotocalini** [comment]
Hi @Tozapid,

It seems that your jenkins server is taking too much time to return the value and the script is not taking the right value that can be the reason.
I will introduce a fix to take a default value ;).

Regards,
Sergio

**Comment by sergiotocalini** [comment]
I am closing this issue because I didn't have any response.
