### ISSUE TITLE
https problem

### ISSUE THREAD

**Issue by itkroplis** [sergiotocalini/jenkix#3]
Hi!

I try 

JENKINS_URL | https://domain.com/jenkins    + transporting traffic nginx
-- | --
(I use godady wildcard certificate)
Debian 9  after zabbix aggent restart ended with error.

Test with Ubuntu 16.4 and http://localhost:8080  work well

What is the solution?

**Comment by sergiotocalini** [comment]
It is really strange I am using in several installation and it work properly, can you paste a log or which is the error?

**Comment by sergiotocalini** [comment]
I've just added the --insecure flag to the curl command.

**Comment by itkroplis** [comment]
I seem that the problem no https. I try different values. And Zabbix aggent conf after add
#jenkix
UserParameter=jenkix[*],/etc/zabbix/scripts/agentd/jenkix/jenkix.sh -s "$1" -a p="$2" -a p="$3" -a p="$4" -a p="$5"
UserParameter=jenkix.discovery[*],/etc/zabbix/scripts/agentd/jenkix/jenkix.sh -a "$1" -j p="$2" -a p="$3"
UserParameter=jenkix.version,/etc/zabbix/scripts/agentd/jenkix/jenkix.sh -v short
Error at start.

ubuntu 16.4  zabbix aggent | 2.4.7
debian9        zabbix aggent | 3.4.5


Maybe need specific zabbix aggent version? Or for Debian9 need another dependency apps.  With ubuntu 16.4 work well.
