### ISSUE TITLE
Error for this Zabbix Items [Jenkins] Service: Uptime  [Jenkins] Service: Listening

### ISSUE THREAD

**Issue by itkroplis** [sergiotocalini/jenkix#4]
Ubuntu 16.4  
Error for this Zabbix Items:
[Jenkins] Service: Uptime
Value "sudo: no tty present and no askpass program specified
0" of type "string" is not suitable for value type "Numeric (unsigned)

[Jenkins] Service: Listening
Value "sudo: no tty present and no askpass program specified
0" of type "string" is not suitable for value type "Numeric (unsigned)"

In /etc/sudoers  I add:
zabbix ALL=(ALL) NOPASSWD: ALL

**Comment by sergiotocalini** [comment]
You need to configure properly your sudo to able to execute commands without tty.
You can do this removing this option on your sudoers:
```
# Defaults    requiretty
```

**Comment by itkroplis** [comment]
Snx,  is good!
zabbix ALL=(ALL) NOPASSWD: ALL
zabbix ALL=NOPASSWD: ALL
