### ISSUE TITLE
About Jenkins http port 8081 and prefix /jenkins!

### ISSUE THREAD

**Issue by itkroplis** [sergiotocalini/jenkix#5]
Hi!
I use Jenkins with 
HTTP_PORT=8081
PREFIX=/jenkins

I install Jenkix  but in my Zabbix I see error
Value "lsof: unacceptable port specification in: -i :8081jenkins
lsof 4.89

OS= Debian 9.4

How is possible resolved it?

**Comment by itkroplis** [comment]
Ok I finded answer.  Need JENKINS_URL="http://localhost:8081"  without prefix value /jenkins

**Comment by sergiotocalini** [comment]
Indeed, you should use without the prefix, anyway I will add a regex to prevent this, thanks for letting me know.
